// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show Firebase, FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// import 'firebase_options.dart';
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///    options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

Future<void> initializeFirebase() async {
  //await Firebase.initializeApp();
  await Firebase.initializeApp(
   options: DefaultFirebaseOptions.currentPlatform,
  );
}


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs7JeahYFjOY7FtPIYneA5ZRmNSrHnpok',
    appId: '1:505371924663:web:ac0498cd49c2c5c567d532',
    messagingSenderId: '505371924663',
    projectId: 'madv-todo',
    authDomain: 'madv-todo.firebaseapp.com',
    storageBucket: 'madv-todo.appspot.com',
    measurementId: 'G-YNZVJ6ESWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFdhfycgmnW8swm8fJrvETirN3ESv7HxM',
    appId: '1:505371924663:android:779a82b43689844967d532',
    messagingSenderId: '505371924663',
    projectId: 'madv-todo',
    storageBucket: 'madv-todo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClYu7WCeeoN_T1zCYRXFjCK0gs-cRyOfo',
    appId: '1:505371924663:ios:c2f59b19c87020ed67d532',
    messagingSenderId: '505371924663',
    projectId: 'madv-todo',
    storageBucket: 'madv-todo.appspot.com',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClYu7WCeeoN_T1zCYRXFjCK0gs-cRyOfo',
    appId: '1:505371924663:ios:c00db5928758d13b67d532',
    messagingSenderId: '505371924663',
    projectId: 'madv-todo',
    storageBucket: 'madv-todo.appspot.com',
    iosBundleId: 'com.example.todolist.RunnerTests',
  );
}
